/**
 *  Built-in commands in Visual Studio Code.
 *  These commands are powered by the VS Code API and are available via the Command Palette.
 */
export const BuiltInCommands = {
  "Exit Zen Mode": "workbench.action.exitZenMode",
  "Close Reference Search": "closeReferenceSearch",
  "Close Test Peek": "editor.closeTestPeek",
  "Cancel Selection": "cancelSelection",
  "Move Cursor To Bottom": "cursorBottom",
  "Select Text To Bottom": "cursorBottomSelect",
  "Column Select Down": "cursorColumnSelectDown",
  "Column Select Left": "cursorColumnSelectLeft",
  "Column Select Page Down": "cursorColumnSelectPageDown",
  "Column Select Page Up": "cursorColumnSelectPageUp",
  "Column Select Right": "cursorColumnSelectRight",
  "Column Select Up": "cursorColumnSelectUp",
  "Move Cursor Down": "cursorDown",
  "Select Text Down": "cursorDownSelect",
  "Move Cursor To End": "cursorEnd",
  "Select Text To End": "cursorEndSelect",
  "Move Cursor To Home": "cursorHome",
  "Select Text To Home": "cursorHomeSelect",
  "Move Cursor Left": "cursorLeft",
  "Select Text Left": "cursorLeftSelect",
  "Move Cursor To Line End": "cursorLineEnd",
  "Select Text To Line End": "cursorLineEndSelect",
  "Move Cursor To Line Start": "cursorLineStart",
  "Select Text To Line Start": "cursorLineStartSelect",
  "Move Cursor Page Down": "cursorPageDown",
  "Select Text Page Down": "cursorPageDownSelect",
  "Move Cursor Page Up": "cursorPageUp",
  "Select Text Page Up": "cursorPageUpSelect",
  "Move Cursor Right": "cursorRight",
  "Select Text Right": "cursorRightSelect",
  "Move Cursor To Top": "cursorTop",
  "Select Text To Top": "cursorTopSelect",
  "Move Cursor Up": "cursorUp",
  "Select Text Up": "cursorUpSelect",
  "Delete Left": "deleteLeft",
  "Delete Right": "deleteRight",
  "Select All": "editor.action.selectAll",
  "Copy": "execCopy",
  "Cut": "execCut",
  "Paste": "execPaste",
  "Expand Line Selection": "expandLineSelection",
  "Inline Chat Arrow Out Down": "inlineChat.arrowOutDown",
  "Inline Chat Arrow Out Up": "inlineChat.arrowOutUp",
  "Insert Line Break": "lineBreakInsert",
  "Outdent": "outdent",
  "Redo": "redo",
  "Scroll Line Down": "scrollLineDown",
  "Scroll Line Up": "scrollLineUp",
  "Scroll Page Down": "scrollPageDown",
  "Scroll Page Up": "scrollPageUp",
  "Tab": "tab",
  "Undo": "undo",
  "Remove Secondary Cursors": "removeSecondaryCursors",
  "Notebook Cell Chat Arrow Out Down": "notebook.cell.chat.arrowOutDown",
  "Notebook Cell Chat Arrow Out Up": "notebook.cell.chat.arrowOutUp",
  "Focus Chat Widget": "notebook.cell.focusChatWidget",
  "Focus Next Chat Widget": "notebook.cell.focusNextChatWidget",
  "Inline Chat Focus": "inlineChat.focus",
  "Accept Notebook Cell Chat Changes": "notebook.cell.chat.acceptChanges",
  "Next From Notebook Cell Chat History": "notebook.cell.chat.nextFromHistory",
  "Previous From Notebook Cell Chat History": "notebook.cell.chat.previousFromHistory",
  "Go To Next Reference": "references-view.next",
  "Go To Previous Reference": "references-view.prev",
  "Apply Refactor Preview": "refactorPreview.apply",
  "Edit Focused Test": "testing.editFocusedTest",
  "Quit Notebook Cell Edit": "notebook.cell.quitEdit",
  "Discard Inline Chat": "inlineChat.discard",
  "Find": "actions.find",
  "Find With Selection": "actions.findWithSelection",
  "Accept Breakpoint Widget Input": "breakpointWidget.action.acceptInput",
  "Focus Chat Action": "chat.action.focus",
  "Close Breakpoint Widget": "closeBreakpointWidget",
  "Cursor Undo": "cursorUndo",
  "Cursor Word End Right": "cursorWordEndRight",
  "Select Word End Right": "cursorWordEndRightSelect",
  "Cursor Word Left": "cursorWordLeft",
  "Select Word Left": "cursorWordLeftSelect",
  "Cursor Word Part Left": "cursorWordPartLeft",
  "Select Word Part Left": "cursorWordPartLeftSelect",
  "Cursor Word Part Right": "cursorWordPartRight",
  "Select Word Part Right": "cursorWordPartRightSelect",
  "Delete All Left": "deleteAllLeft",
  "Delete All Right": "deleteAllRight",
  "Delete Word Left": "deleteWordLeft",
  "Delete Word Part Left": "deleteWordPartLeft",
  "Delete Word Part Right": "deleteWordPartRight",
  "Delete Word Right": "deleteWordRight",
  "Next Accessible Diff Viewer": "editor.action.accessibleDiffViewer.next",
  "Previous Accessible Diff Viewer": "editor.action.accessibleDiffViewer.prev",
  "Add Comment Line": "editor.action.addCommentLine",
  "Add Selection To Next Find Match": "editor.action.addSelectionToNextFindMatch",
  "Auto Fix": "editor.action.autoFix",
  "Block Comment": "editor.action.blockComment",
  "Cancel Selection Anchor": "editor.action.cancelSelectionAnchor",
  "Change All": "editor.action.changeAll",
  "Clipboard Copy Action": "editor.action.clipboardCopyAction",
  "Clipboard Cut Action": "editor.action.clipboardCutAction",
  "Clipboard Paste Action": "editor.action.clipboardPasteAction",
  "Comment Line": "editor.action.commentLine",
  "Copy Lines Down Action": "editor.action.copyLinesDownAction",
  "Copy Lines Up Action": "editor.action.copyLinesUpAction",
  "Delete Lines": "editor.action.deleteLines",
  "Next Dirty Diff": "editor.action.dirtydiff.next",
  "Previous Dirty Diff": "editor.action.dirtydiff.previous",
  "Find Next In Extension Editor": "editor.action.extensioneditor.findNext",
  "Find Previous In Extension Editor": "editor.action.extensioneditor.findPrevious",
  "Show Find In Extension Editor": "editor.action.extensioneditor.showfind",
  "Format Document": "editor.action.formatDocument",
  "Format Selection": "editor.action.formatSelection",
  "Go To Bottom Hover": "editor.action.goToBottomHover",
  "Go To Focused Sticky Scroll Line": "editor.action.goToFocusedStickyScrollLine",
  "Go To Implementation": "editor.action.goToImplementation",
  "Go To References": "editor.action.goToReferences",
  "Go To Top Hover": "editor.action.goToTopHover",
  "Hide Color Picker": "editor.action.hideColorPicker",
  "In Place Replace Down": "editor.action.inPlaceReplace.down",
  "In Place Replace Up": "editor.action.inPlaceReplace.up",
  "Indent Lines": "editor.action.indentLines",
  "Reject Inline Edit": "editor.action.inlineEdit.reject",
  "Hide Inline Edits": "editor.action.inlineEdits.hide",
  "Show Next Inline Edits": "editor.action.inlineEdits.showNext",
  "Show Previous Inline Edits": "editor.action.inlineEdits.showPrevious",
  "Hide Inline Suggest": "editor.action.inlineSuggest.hide",
  "Show Next Inline Suggest": "editor.action.inlineSuggest.showNext",
  "Show Previous Inline Suggest": "editor.action.inlineSuggest.showPrevious",
  "Insert Color With Standalone Color Picker": "editor.action.insertColorWithStandaloneColorPicker",
  "Insert Cursor Above": "editor.action.insertCursorAbove",
  "Insert Cursor At End Of Each Line Selected": "editor.action.insertCursorAtEndOfEachLineSelected",
  "Insert Cursor Below": "editor.action.insertCursorBelow",
  "Insert Line After": "editor.action.insertLineAfter",
  "Insert Line Before": "editor.action.insertLineBefore",
  "Join Lines": "editor.action.joinLines",
  "Jump To Bracket": "editor.action.jumpToBracket",
  "Linked Editing": "editor.action.linkedEditing",
  "Next Marker": "editor.action.marker.next",
  "Next Marker In Files": "editor.action.marker.nextInFiles",
  "Previous Marker": "editor.action.marker.prev",
  "Previous Marker In Files": "editor.action.marker.prevInFiles",
  "Move Lines Down Action": "editor.action.moveLinesDownAction",
  "Move Lines Up Action": "editor.action.moveLinesUpAction",
  "Move Selection To Next Find Match": "editor.action.moveSelectionToNextFindMatch",
  "Next Comment Thread Action": "editor.action.nextCommentThreadAction",
  "Next Commenting Range": "editor.action.nextCommentingRange",
  "Next Match Find Action": "editor.action.nextMatchFindAction",
  "Next Selection Match Find Action": "editor.action.nextSelectionMatchFindAction",
  "Organize Imports": "editor.action.organizeImports",
  "Outdent Lines": "editor.action.outdentLines",
  "Page Down Hover": "editor.action.pageDownHover",
  "Page Up Hover": "editor.action.pageUpHover",
  "Peek Definition": "editor.action.peekDefinition",
  "Peek Implementation": "editor.action.peekImplementation",
  "Previous Comment Thread Action": "editor.action.previousCommentThreadAction",
  "Previous Commenting Range": "editor.action.previousCommentingRange",
  "Previous Match Find Action": "editor.action.previousMatchFindAction",
  "Previous Selection Match Find Action": "editor.action.previousSelectionMatchFindAction",
  "Quick Fix": "editor.action.quickFix",
  "Refactor": "editor.action.refactor",
  "Remove Brackets": "editor.action.removeBrackets",
  "Remove Comment Line": "editor.action.removeCommentLine",
  "Rename": "editor.action.rename",
  "Reveal Definition": "editor.action.revealDefinition",
  "Reveal Definition Aside": "editor.action.revealDefinitionAside",
  "Scroll Down Hover": "editor.action.scrollDownHover",
  "Scroll Left Hover": "editor.action.scrollLeftHover",
  "Scroll Right Hover": "editor.action.scrollRightHover",
  "Scroll Up Hover": "editor.action.scrollUpHover",
  "Select Editor": "editor.action.selectEditor",
  "Select From Anchor To Cursor": "editor.action.selectFromAnchorToCursor",
  "Select Highlights": "editor.action.selectHighlights",
  "Select Next Sticky Scroll Line": "editor.action.selectNextStickyScrollLine",
  "Select Previous Sticky Scroll Line": "editor.action.selectPreviousStickyScrollLine",
  "Set Selection Anchor": "editor.action.setSelectionAnchor",
  "Show Context Menu": "editor.action.showContextMenu",
  "Show Hover": "editor.action.showHover",
  "Expand Smart Select": "editor.action.smartSelect.expand",
  "Shrink Smart Select": "editor.action.smartSelect.shrink",
  "Start Find Replace Action": "editor.action.startFindReplaceAction",
  "Submit Comment": "editor.action.submitComment",
  "Toggle Tab Focus Mode": "editor.action.toggleTabFocusMode",
  "Toggle Word Wrap": "editor.action.toggleWordWrap",
  "Transpose Letters": "editor.action.transposeLetters",
  "Trigger Parameter Hints": "editor.action.triggerParameterHints",
  "Trigger Suggest": "editor.action.triggerSuggest",
  "Trim Trailing Whitespace": "editor.action.trimTrailingWhitespace",
  "Find Next In Webview Editor": "editor.action.webvieweditor.findNext",
  "Find Previous In Webview Editor": "editor.action.webvieweditor.findPrevious",
  "Hide Find In Webview Editor": "editor.action.webvieweditor.hideFind",
  "Show Find In Webview Editor": "editor.action.webvieweditor.showFind",
  "Go To Next Word Highlight": "editor.action.wordHighlight.next",
  "Go To Previous Word Highlight": "editor.action.wordHighlight.prev",
  "Cancel Operation": "editor.cancelOperation",
  "Change Drop Type": "editor.changeDropType",
  "Change Paste Type": "editor.changePasteType",
  "Create Folding Range From Selection": "editor.createFoldingRangeFromSelection",
  "Close Exception Widget In Debug Action": "editor.debug.action.closeExceptionWidget",
  "Show Debug Hover In Debug Action": "editor.debug.action.showDebugHover",
  "Toggle Breakpoint In Debug Action": "editor.debug.action.toggleBreakpoint",
  "Expand Abbreviation In Emmet Action": "editor.emmet.action.expandAbbreviation",
  "Fold Editor": "editor.fold",
  "Fold All In Editor": "editor.foldAll",
  "Fold All Block Comments In Editor": "editor.foldAllBlockComments",
  "Fold All Except In Editor": "editor.foldAllExcept",
  "Fold All Marker Regions In Editor": "editor.foldAllMarkerRegions",
  "Fold Level 1 In Editor": "editor.foldLevel1",
  "Fold Level 2 In Editor": "editor.foldLevel2",
  "Fold Level 3 In Editor": "editor.foldLevel3",
  "Fold Level 4 In Editor": "editor.foldLevel4",
  "Fold Level 5 In Editor": "editor.foldLevel5",
  "Fold Level 6 In Editor": "editor.foldLevel6",
  "Fold Level 7 In Editor": "editor.foldLevel7",
  "Fold Recursively In Editor": "editor.foldRecursively",
  "Go To Next Symbol From Result": "editor.gotoNextSymbolFromResult",
  "Cancel Go To Next Symbol From Result": "editor.gotoNextSymbolFromResult.cancel",
  "Hide Drop Widget": "editor.hideDropWidget",
  "Hide Paste Widget": "editor.hidePasteWidget",
  "Remove Manual Folding Ranges": "editor.removeManualFoldingRanges",
  "Toggle Fold In Editor": "editor.toggleFold",
  "Toggle Fold Recursively In Editor": "editor.toggleFoldRecursively",
  "Unfold Editor": "editor.unfold",
  "Unfold All In Editor": "editor.unfoldAll",
  "Unfold All Except In Editor": "editor.unfoldAllExcept",
  "Unfold All Marker Regions In Editor": "editor.unfoldAllMarkerRegions",
  "Unfold Recursively In Editor": "editor.unfoldRecursively",
  "Stop Reading Line With Hint": "inlayHints.stopReadingLineWithHint",
  "Insert Snippet": "insertSnippet",
  "Execute In Interactive": "interactive.execute",
  "Discard Cell Chat In Notebook": "notebook.cell.chat.discard",
  "Cursor Page Down In Notebook Cell": "notebook.cell.cursorPageDown",
  "Cursor Page Down Select In Notebook Cell": "notebook.cell.cursorPageDownSelect",
  "Cursor Page Up In Notebook Cell": "notebook.cell.cursorPageUp",
  "Cursor Page Up Select In Notebook Cell": "notebook.cell.cursorPageUpSelect",
  "Execute Notebook Cell": "notebook.cell.execute",
  "Execute And Insert Below Notebook Cell": "notebook.cell.executeAndInsertBelow",
  "Execute And Select Below Notebook Cell": "notebook.cell.executeAndSelectBelow",
  "Paste Above Notebook Cell": "notebook.cell.pasteAbove",
  "Focus Next Editor In Notebook": "notebook.focusNextEditor",
  "Focus Previous Editor In Notebook": "notebook.focusPreviousEditor",
  "Format Cell In Notebook": "notebook.formatCell",
  "Open Reference To Side": "openReferenceToSide",
  "Accept Input In Repl Action": "repl.action.acceptInput",
  "Filter In Repl Action": "repl.action.filter",
  "Find In Repl Action": "repl.action.find",
  "Execute In Repl": "repl.execute",
  "Rerun Search Editor Search": "rerunSearchEditorSearch",
  "Focus Query Editor Widget In Search Action": "search.action.focusQueryEditorWidget",
  "Delete File Results In Search Editor Action": "search.searchEditor.action.deleteFileResults",
  "Clear Search Results In Settings Action": "settings.action.clearSearchResults",
  "Focus Settings File In Settings Action": "settings.action.focusSettingsFile",
  "Search In Settings Action": "settings.action.search",
  "Toggle Explain Mode": "toggleExplainMode",
  "Toggle Peek Widget Focus": "togglePeekWidgetFocus",
  "Go Back In Welcome": "welcome.goBack",
  "Add Comment In Workbench Action": "workbench.action.addComment",
  "Attach Context In Chat Workbench Action": "workbench.action.chat.attachContext",
  "Run In Terminal In Chat Workbench Action": "workbench.action.chat.runInTerminal",
  "Submit In Chat Workbench Action": "workbench.action.chat.submit",
  "Submit Secondary Agent In Chat Workbench Action": "workbench.action.chat.submitSecondaryAgent",
  "Go To Next Change In Editor": "workbench.action.editor.nextChange",
  "Go To Previous Change In Editor": "workbench.action.editor.previousChange",
  "Hide Comment In Workbench Action": "workbench.action.hideComment",
  "Accept Inline Edit In Editor": "editor.action.inlineEdit.accept",
  "Jump To Inline Edit In Editor": "editor.action.inlineEdit.jumpTo",
  "Trigger Inline Edit In Editor": "editor.action.inlineEdit.trigger",
  "Accept Next Word In Inline Suggest": "editor.action.inlineSuggest.acceptNextWord",
  "Go To Next Message In Testing": "testing.goToNextMessage",
  "Go To Previous Message In Testing": "testing.goToPreviousMessage",
  "Close Find Widget": "closeFindWidget",
  "Replace All In Editor": "editor.action.replaceAll",
  "Replace One In Editor": "editor.action.replaceOne",
  "Select All Matches In Editor": "editor.action.selectAllMatches",
  "Toggle Find Case Sensitive": "toggleFindCaseSensitive",
  "Toggle Find In Selection": "toggleFindInSelection",
  "Toggle Find Regex": "toggleFindRegex",
  "Toggle Find Whole Word": "toggleFindWholeWord",
  "Toggle Preserve Case": "togglePreserveCase",
  "Jump Back In Inline Edit": "editor.action.inlineEdit.jumpBack",
  "Jump To Next Snippet Placeholder": "jumpToNextSnippetPlaceholder",
  "Jump To Previous Snippet Placeholder": "jumpToPrevSnippetPlaceholder",
  "Leave Editor Message": "leaveEditorMessage",
  "Leave Snippet": "leaveSnippet",
  "Close Dirty Diff": "closeDirtyDiff",
  "Close Markers Navigation": "closeMarkersNavigation",
  "Hide Notifications Toasts": "notifications.hideToasts",
  "Close Parameter Hints": "closeParameterHints",
  "Show Next Parameter Hint": "showNextParameterHint",
  "Show Previous Parameter Hint": "showPrevParameterHint",
  "Accept Alternative Selected Suggestion": "acceptAlternativeSelectedSuggestion",
  "Accept Selected Suggestion": "acceptSelectedSuggestion",
  "Focus Suggestion": "focusSuggestion",
  "Hide Suggest Widget": "hideSuggestWidget",
  "Insert Best Completion": "insertBestCompletion",
  "Insert Next Suggestion": "insertNextSuggestion",
  "Insert Previous Suggestion": "insertPrevSuggestion",
  "Select Next Page Suggestion": "selectNextPageSuggestion",
  "Select Next Suggestion": "selectNextSuggestion",
  "Select Previous Page Suggestion": "selectPrevPageSuggestion",
  "Select Previous Suggestion": "selectPrevSuggestion",
  "Toggle Suggestion Details": "toggleSuggestionDetails",
  "Toggle Suggestion Focus": "toggleSuggestionFocus",
  "Accept Rename Input": "acceptRenameInput",
  "Accept Rename Input With Preview": "acceptRenameInputWithPreview",
  "Cancel Linked Editing Input": "cancelLinkedEditingInput",
  "Cancel Rename Input": "cancelRenameInput",
  "Focus Next Rename Suggestion": "focusNextRenameSuggestion",
  "Focus Previous Rename Suggestion": "focusPreviousRenameSuggestion",
  "Add Cursors At Search Results": "addCursorsAtSearchResults",
  "Focus Breadcrumbs": "breadcrumbs.focus",
  "Focus And Select Breadcrumbs": "breadcrumbs.focusAndSelect",
  "Focus Next Breadcrumb": "breadcrumbs.focusNext",
  "Focus Previous Breadcrumb": "breadcrumbs.focusPrevious",
  "Reveal Focused Breadcrumb": "breadcrumbs.revealFocused",
  "Reveal Focused Breadcrumb From Tree Aside": "breadcrumbs.revealFocusedFromTreeAside",
  "Select Focused Breadcrumb": "breadcrumbs.selectFocused",
  "Toggle Breadcrumbs To On": "breadcrumbs.toggleToOn",
  "Close Replace In Files Widget": "closeReplaceInFilesWidget",
  "Clear Filter Text In Comments": "commentsClearFilterText",
  "Focus On Comments Filter": "commentsFocusFilter",
  "Focus On View From Comments Filter": "commentsFocusViewFromFilter",
  "Copy File Path": "copyFilePath",
  "Copy Relative File Path": "copyRelativeFilePath",
  "Open Breakpoint To Side In Debug Mode": "debug.openBreakpointToSide",
  "Open Debug View": "debug.openView",
  "Remove Breakpoint In Debug Mode": "debug.removeBreakpoint",
  "Remove Watch Expression In Debug Mode": "debug.removeWatchExpression",
  "Decrease Search Editor Context Lines": "decreaseSearchEditorContextLines",
  "Open Accessibility Help": "editor.action.accessibilityHelp",
  "Configure Assigned Keybindings For Accessibility Help": "editor.action.accessibilityHelpConfigureAssignedKeybindings",
  "Configure Keybindings For Accessibility Help": "editor.action.accessibilityHelpConfigureKeybindings",
  "Open Help Link For Accessibility Help": "editor.action.accessibilityHelpOpenHelpLink",
  "Open Accessible View": "editor.action.accessibleView",
  "Accept Inline Completion In Accessible View": "editor.action.accessibleViewAcceptInlineCompletion",
  "Disable Hint In Accessible View": "editor.action.accessibleViewDisableHint",
  "Move To Next In Accessible View": "editor.action.accessibleViewNext",
  "Move To Next Code Block In Accessible View": "editor.action.accessibleViewNextCodeBlock",
  "Move To Previous In Accessible View": "editor.action.accessibleViewPrevious",
  "Move To Previous Code Block In Accessible View": "editor.action.accessibleViewPreviousCodeBlock",
  "Define Keybinding In Editor": "editor.action.defineKeybinding",
  "Commit Inline Suggestion In Editor": "editor.action.inlineSuggest.commit",
  "Toggle Inline Breakpoint In Debug Editor": "editor.debug.action.toggleInlineBreakpoint",
  "Detect Language In Editor": "editor.detectLanguage",
  "Refocus Call Hierarchy In Editor": "editor.refocusCallHierarchy",
  "Refocus Type Hierarchy In Editor": "editor.refocusTypeHierarchy",
  "Show Call Hierarchy In Editor": "editor.showCallHierarchy",
  "Show Incoming Calls In Editor": "editor.showIncomingCalls",
  "Show Outgoing Calls In Editor": "editor.showOutgoingCalls",
  "Show Subtypes In Editor": "editor.showSubtypes",
  "Show Supertypes In Editor": "editor.showSupertypes",
  "Open To Side In Explorer": "explorer.openToSide",
  "Find In Folder In Files Explorer": "filesExplorer.findInFolder",
  "Show Next In History": "history.showNext",
  "Show Previous In History": "history.showPrevious",
  "Focus Down In Icon Select Box": "iconSelectBox.focusDown",
  "Focus Next In Icon Select Box": "iconSelectBox.focusNext",
  "Focus Previous In Icon Select Box": "iconSelectBox.focusPrevious",
  "Focus Up In Icon Select Box": "iconSelectBox.focusUp",
  "Select Focused In Icon Select Box": "iconSelectBox.selectFocused",
  "Increase Search Editor Context Lines": "increaseSearchEditorContextLines",
  "Close Inline Chat": "inlineChat.close",
  "Discard Hunk Change In Inline Chat": "inlineChat.discardHunkChange",
  "Hold For Speech In Inline Chat": "inlineChat.holdForSpeech",
  "Move To Next Hunk In Inline Chat": "inlineChat.moveToNextHunk",
  "Move To Previous Hunk In Inline Chat": "inlineChat.moveToPreviousHunk",
  "Regenerate In Inline Chat": "inlineChat.regenerate",
  "Start Inline Chat": "inlineChat.start",
  "Unstash In Inline Chat": "inlineChat.unstash",
  "View In Chat In Inline Chat": "inlineChat.viewInChat",
  "Show Next In Interactive History": "interactive.history.next",
  "Show Previous In Interactive History": "interactive.history.previous",
  "Scroll To Bottom In Interactive": "interactive.scrollToBottom",
  "Scroll To Top In Interactive": "interactive.scrollToTop",
  "Accept When Expression In Keybindings Editor": "keybindings.editor.acceptWhenExpression",
  "Add Keybinding In Keybindings Editor": "keybindings.editor.addKeybinding",
  "Clear Search Results In Keybindings Editor": "keybindings.editor.clearSearchResults",
  "Copy Keybinding Entry In Keybindings Editor": "keybindings.editor.copyKeybindingEntry",
  "Define Keybinding In Keybindings Editor": "keybindings.editor.defineKeybinding",
  "Define When Expression In Keybindings Editor": "keybindings.editor.defineWhenExpression",
  "Focus Keybindings In Keybindings Editor": "keybindings.editor.focusKeybindings",
  "Record Search Keys In Keybindings Editor": "keybindings.editor.recordSearchKeys",
  "Reject When Expression In Keybindings Editor": "keybindings.editor.rejectWhenExpression",
  "Remove Keybinding In Keybindings Editor": "keybindings.editor.removeKeybinding",
  "Search Keybindings In Keybindings Editor": "keybindings.editor.searchKeybindings",
  "Toggle Sort By Precedence In Keybindings Editor": "keybindings.editor.toggleSortByPrecedence",
  "Clear List": "list.clear",
  "Close Find In List": "list.closeFind",
  "Collapse List": "list.collapse",
  "Collapse All In List": "list.collapseAll",
  "Expand List": "list.expand",
  "Expand Selection Down In List": "list.expandSelectionDown",
  "Expand Selection Up In List": "list.expandSelectionUp",
  "Find In List": "list.find",
  "Focus Any Down In List": "list.focusAnyDown",
  "Focus Any First In List": "list.focusAnyFirst",
  "Focus Any Last In List": "list.focusAnyLast",
  "Focus Any Up In List": "list.focusAnyUp",
  "Focus Down In List": "list.focusDown",
  "Focus First In List": "list.focusFirst",
  "Focus Last In List": "list.focusLast",
  "Focus Page Down In List": "list.focusPageDown",
  "Focus Page Up In List": "list.focusPageUp",
  "Focus Up In List": "list.focusUp",
  "Scroll Down In List": "list.scrollDown",
  "Scroll Up In List": "list.scrollUp",
  "Select In List": "list.select",
  "Select All In List": "list.selectAll",
  "Show Hover In List": "list.showHover",
  "Toggle Expand In List": "list.toggleExpand",
  "Toggle Selection In List": "list.toggleSelection",
  "Delete Left In Note Multi Cursor": "noteMultiCursor.deleteLeft",
  "Exit Note Multi Cursor": "noteMultiCursor.exit",
  "Add Find Match To Selection In Notebook": "notebook.addFindMatchToSelection",
  "Change To Code In Notebook Cell": "notebook.cell.changeToCode",
  "Change To Markdown In Notebook Cell": "notebook.cell.changeToMarkdown",
  "Accept Chat In Notebook Cell": "notebook.cell.chat.accept",
  "Focus In Notebook Cell Chat": "notebook.cell.chat.focus",
  "Focus Next Cell In Notebook Cell Chat": "notebook.cell.chat.focusNextCell",
  "Focus Previous Cell In Notebook Cell Chat": "notebook.cell.chat.focusPreviousCell",
  "Start Notebook Cell Chat": "notebook.cell.chat.start",
  "Clear Outputs In Notebook Cell": "notebook.cell.clearOutputs",
  "Collapse Cell Input In Notebook Cell": "notebook.cell.collapseCellInput",
  "Collapse Cell Output In Notebook Cell": "notebook.cell.collapseCellOutput",
  "Copy Down In Notebook Cell": "notebook.cell.copyDown",
  "Copy Up In Notebook Cell": "notebook.cell.copyUp",
  "Delete Notebook Cell": "notebook.cell.delete",
  "Detect Language In Notebook Cell": "notebook.cell.detectLanguage",
  "Edit Notebook Cell": "notebook.cell.edit",
  "Expand Cell Input In Notebook Cell": "notebook.cell.expandCellInput",
  "Expand Cell Output In Notebook Cell": "notebook.cell.expandCellOutput",
  "Focus In Output In Notebook Cell": "notebook.cell.focusInOutput",
  "Focus Out Output In Notebook Cell": "notebook.cell.focusOutOutput",
  "Insert Code Cell Above In Notebook Cell": "notebook.cell.insertCodeCellAbove",
  "Insert Code Cell Below In Notebook Cell": "notebook.cell.insertCodeCellBelow",
  "Join Above In Notebook Cell": "notebook.cell.joinAbove",
  "Join Below In Notebook Cell": "notebook.cell.joinBelow",
  "Move Down In Notebook Cell": "notebook.cell.moveDown",
  "Move Up In Notebook Cell": "notebook.cell.moveUp",
  "Open Failure Actions In Notebook Cell": "notebook.cell.openFailureActions",
  "Split Notebook Cell": "notebook.cell.split",
  "Toggle Output Scrolling In Notebook Cell": "notebook.cell.toggleOutputScrolling",
  "Center Active Cell In Notebook": "notebook.centerActiveCell",
  "Comment Selected Cells In Notebook": "notebook.commentSelectedCells",
  "Move To Next Action In Notebook Diff": "notebook.diff.action.next",
  "Move To Previous Action In Notebook Diff": "notebook.diff.action.previous",
  "Find In Notebook": "notebook.find",
  "Focus Bottom In Notebook": "notebook.focusBottom",
  "Focus Top In Notebook": "notebook.focusTop",
  "Fold In Notebook": "notebook.fold",
  "Format In Notebook": "notebook.format",
  "Hide Find In Notebook": "notebook.hideFind",
  "Unfold In Notebook": "notebook.unfold",
  "Accept Primary Action In Notification": "notification.acceptPrimaryAction",
  "Clear Notification": "notification.clear",
  "Collapse Notification": "notification.collapse",
  "Expand Notification": "notification.expand",
  "Toggle Notification": "notification.toggle",
  "Focus First Toast In Notifications": "notifications.focusFirstToast",
  "Focus Last Toast In Notifications": "notifications.focusLastToast",
  "Focus Next Toast In Notifications": "notifications.focusNextToast",
  "Focus Previous Toast In Notifications": "notifications.focusPreviousToast",
  "Show List In Notifications": "notifications.showList",
  "Clear Filter Text In Problems Action": "problems.action.clearFilterText",
  "Copy In Problems Action": "problems.action.copy",
  "Focus Filter In Problems Action": "problems.action.focusFilter",
  "Focus Problems From Filter In Problems Action": "problems.action.focusProblemsFromFilter",
  "Open In Problems Action": "problems.action.open",
  "Open To Side In Problems Action": "problems.action.openToSide",
  "Show Quick Fixes In Problems Action": "problems.action.showQuickFixes",
  "Move To First In Quick Input": "quickInput.first",
  "Move To Last In Quick Input": "quickInput.last",
  "Move To Next In Quick Input": "quickInput.next",
  "Move To Next Separator In Quick Input": "quickInput.nextSeparator",
  "Move To Next Separator With Quick Access Fallback In Quick Input": "quickInput.nextSeparatorWithQuickAccessFallback",
  "Page Next In Quick Input": "quickInput.pageNext",
  "Go To Previous Page In Quick Input": "quickInput.pagePrevious",
  "Go To Previous Item In Quick Input": "quickInput.previous",
  "Go To Previous Separator In Quick Input": "quickInput.previousSeparator",
  "Toggle Checked State In Refactor Preview": "refactorPreview.toggleCheckedState",
  "Reveal File In Operating System": "revealFileInOS",
  "Reveal Reference": "revealReference",
  "Save All Files": "saveAll",
  "Accept Input In Source Control": "scm.acceptInput",
  "Clear Input In Source Control": "scm.clearInput",
  "Force View Next Commit In Source Control": "scm.forceViewNextCommit",
  "Force View Previous Commit In Source Control": "scm.forceViewPreviousCommit",
  "View Next Commit In Source Control": "scm.viewNextCommit",
  "View Previous Commit In Source Control": "scm.viewPreviousCommit",
  "Cancel Search": "search.action.cancel",
  "Copy Match In Search": "search.action.copyMatch",
  "Copy Path In Search": "search.action.copyPath",
  "Focus Next Search Result": "search.action.focusNextSearchResult",
  "Focus Previous Search Result": "search.action.focusPreviousSearchResult",
  "Focus Search From Results": "search.action.focusSearchFromResults",
  "Open In Editor From Search": "search.action.openInEditor",
  "Open Search Result": "search.action.openResult",
  "Open Search Result To Side": "search.action.openResultToSide",
  "Remove From Search": "search.action.remove",
  "Replace In Search": "search.action.replace",
  "Replace All In Search": "search.action.replaceAll",
  "Replace All In File From Search": "search.action.replaceAllInFile",
  "Replace All In Folder From Search": "search.action.replaceAllInFolder",
  "Restrict Search To Folder": "search.action.restrictSearchToFolder",
  "Focus Next Input Box In Search": "search.focus.nextInputBox",
  "Focus Previous Input Box In Search": "search.focus.previousInputBox",
  "Select All Matches In Search Editor": "selectAllSearchEditorMatches",
  "Focus Level Up In Settings": "settings.action.focusLevelUp",
  "Focus Setting Control In Settings": "settings.action.focusSettingControl",
  "Focus Settings From Search": "settings.action.focusSettingsFromSearch",
  "Focus Settings List In Settings": "settings.action.focusSettingsList",
  "Focus Table Of Contents In Settings": "settings.action.focusTOC",
  "Show Context Menu In Settings": "settings.action.showContextMenu",
  "Cancel Test Run": "testing.cancelRun",
  "Cover All Tests": "testing.coverageAll",
  "Cover Tests At Cursor": "testing.coverageAtCursor",
  "Cover Current File Tests": "testing.coverageCurrentFile",
  "Cover Last Run Tests": "testing.coverageLastRun",
  "Debug All Tests": "testing.debugAll",
  "Debug Tests At Cursor": "testing.debugAtCursor",
  "Debug Current File Tests": "testing.debugCurrentFile",
  "Debug Failed Tests": "testing.debugFailTests",
  "Debug Last Run Tests": "testing.debugLastRun",
  "Open Output Peek In Tests": "testing.openOutputPeek",
  "Re-Run Failed Tests": "testing.reRunFailTests",
  "Re-Run Last Run Tests": "testing.reRunLastRun",
  "Refresh Tests": "testing.refreshTests",
  "Run All Tests": "testing.runAll",
  "Run Tests At Cursor": "testing.runAtCursor",
  "Run Current File Tests": "testing.runCurrentFile",
  "Show Most Recent Output In Tests": "testing.showMostRecentOutput",
  "Toggle Inline Coverage In Tests": "testing.toggleInlineCoverage",
  "Toggle Inline Test Output In Tests": "testing.toggleInlineTestOutput",
  "Toggle Testing Peek History": "testing.toggleTestingPeekHistory",
  "Toggle Search Case Sensitivity": "toggleSearchCaseSensitive",
  "Toggle Search Editor Case Sensitivity": "toggleSearchEditorCaseSensitive",
  "Toggle Search Editor Context Lines": "toggleSearchEditorContextLines",
  "Toggle Search Editor Regex": "toggleSearchEditorRegex",
  "Toggle Search Editor Whole Word": "toggleSearchEditorWholeWord",
  "Toggle Search Preserve Case": "toggleSearchPreserveCase",
  "Toggle Search Regex": "toggleSearchRegex",
  "Toggle Search Whole Word": "toggleSearchWholeWord",
  "Show New File Entries In Welcome": "welcome.showNewFileEntries",
  "Focus Next Widget": "widgetNavigation.focusNext",
  "Focus Previous Widget": "widgetNavigation.focusPrevious",
  "Cancel Chat In Workbench": "workbench.action.chat.cancel",
  "Focus Input In Chat": "workbench.action.chat.focusInput",
  "Hold To Voice Chat In Chat View": "workbench.action.chat.holdToVoiceChatInChatView",
  "Start New Chat": "workbench.action.chat.newChat",
  "Go To Next Code Block In Chat": "workbench.action.chat.nextCodeBlock",
  "Go To Next File Tree In Chat": "workbench.action.chat.nextFileTree",
  "Open Chat": "workbench.action.chat.open",
  "Go To Previous Code Block In Chat": "workbench.action.chat.previousCodeBlock",
  "Go To Previous File Tree In Chat": "workbench.action.chat.previousFileTree",
  "Remove From Chat": "workbench.action.chat.remove",
  "Send To New Chat": "workbench.action.chat.sendToNewChat",
  "Start Voice Chat": "workbench.action.chat.startVoiceChat",
  "Stop Listening And Submit In Chat": "workbench.action.chat.stopListeningAndSubmit",
  "Close Active Editor": "workbench.action.closeActiveEditor",
  "Close All Editors": "workbench.action.closeAllEditors",
  "Close All Groups": "workbench.action.closeAllGroups",
  "Close Editors In Group": "workbench.action.closeEditorsInGroup",
  "Close Folder": "workbench.action.closeFolder",
  "Close Group": "workbench.action.closeGroup",
  "Close Other Editors": "workbench.action.closeOtherEditors",
  "Close Quick Open": "workbench.action.closeQuickOpen",
  "Close Unmodified Editors": "workbench.action.closeUnmodifiedEditors",
  "Close Window": "workbench.action.closeWindow",
  "Go To Next Change In Compare Editor": "workbench.action.compareEditor.nextChange",
  "Open Side In Compare Editor": "workbench.action.compareEditor.openSide",
  "Go To Previous Change In Compare Editor": "workbench.action.compareEditor.previousChange",
  "Copy Editor To New Window": "workbench.action.copyEditorToNewWindow",
  "Disconnect Debug": "workbench.action.debug.disconnect",
  "Restart Debug": "workbench.action.debug.restart",
  "Run Debug": "workbench.action.debug.run",
  "Start Debug": "workbench.action.debug.start",
  "Step Into Target In Debug": "workbench.action.debug.stepIntoTarget",
  "Step Out In Debug": "workbench.action.debug.stepOut",
  "Step Over In Debug": "workbench.action.debug.stepOver",
  "Stop Debug": "workbench.action.debug.stop",
  "Change Language Mode In Editor": "workbench.action.editor.changeLanguageMode",
  "Start Dictation In Editor": "workbench.action.editorDictation.start",
  "Copy Path Of Active File": "workbench.action.files.copyPathOfActiveFile",
  "Create New Untitled File": "workbench.action.files.newUntitledFile",
  "Open File": "workbench.action.files.openFile",
  "Open File Or Folder": "workbench.action.files.openFileFolder",
  "Open Folder Via Workspace": "workbench.action.files.openFolderViaWorkspace",
  "Open Local File Or Folder": "workbench.action.files.openLocalFileFolder",
  "Reveal Active File In Windows": "workbench.action.files.revealActiveFileInWindows",
  "Save File": "workbench.action.files.save",
  "Save File As": "workbench.action.files.saveAs",
  "Save Local File": "workbench.action.files.saveLocalFile",
  "Save File Without Formatting": "workbench.action.files.saveWithoutFormatting",
  "Find In Files": "workbench.action.findInFiles",
  "Focus Above Group": "workbench.action.focusAboveGroup",
  "Focus Below Group": "workbench.action.focusBelowGroup",
  "Focus Eighth Editor Group": "workbench.action.focusEighthEditorGroup",
  "Focus Fifth Editor Group": "workbench.action.focusFifthEditorGroup",
  "Focus First Editor Group": "workbench.action.focusFirstEditorGroup",
  "Focus Fourth Editor Group": "workbench.action.focusFourthEditorGroup",
  "Focus Left Group": "workbench.action.focusLeftGroup",
  "Focus Next Part": "workbench.action.focusNextPart",
  "Focus Previous Part": "workbench.action.focusPreviousPart",
  "Focus Right Group": "workbench.action.focusRightGroup",
  "Focus Second Editor Group": "workbench.action.focusSecondEditorGroup",
  "Focus Seventh Editor Group": "workbench.action.focusSeventhEditorGroup",
  "Focus Side Bar": "workbench.action.focusSideBar",
  "Focus Sixth Editor Group": "workbench.action.focusSixthEditorGroup",
  "Focus Third Editor Group": "workbench.action.focusThirdEditorGroup",
  "Go To Line": "workbench.action.gotoLine",
  "Go To Symbol": "workbench.action.gotoSymbol",
  "Arrow Down In Interactive Playground": "workbench.action.interactivePlayground.arrowDown",
  "Arrow Up In Interactive Playground": "workbench.action.interactivePlayground.arrowUp",
  "Page Down In Interactive Playground": "workbench.action.interactivePlayground.pageDown",
  "Page Up In Interactive Playground": "workbench.action.interactivePlayground.pageUp",
  "Join Editor In Group": "workbench.action.joinEditorInGroup",
  "Keep Editor": "workbench.action.keepEditor",
  "Open Keybindings Reference": "workbench.action.keybindingsReference",
  "Go To Last Editor In Group": "workbench.action.lastEditorInGroup",
  "Move Active Editor Group Down": "workbench.action.moveActiveEditorGroupDown",
  "Move Active Editor Group Left": "workbench.action.moveActiveEditorGroupLeft",
  "Move Active Editor Group Right": "workbench.action.moveActiveEditorGroupRight",
  "Move Active Editor Group Up": "workbench.action.moveActiveEditorGroupUp",
  "Move Editor Left In Group": "workbench.action.moveEditorLeftInGroup",
  "Move Editor Right In Group": "workbench.action.moveEditorRightInGroup",
  "Move Editor To First Group": "workbench.action.moveEditorToFirstGroup",
  "Move Editor To Last Group": "workbench.action.moveEditorToLastGroup",
  "Move Editor To Next Group": "workbench.action.moveEditorToNextGroup",
  "Move Editor To Previous Group": "workbench.action.moveEditorToPreviousGroup",
  "Navigate Back": "workbench.action.navigateBack",
  "Navigate Forward": "workbench.action.navigateForward",
  "Navigate To Last Edit Location": "workbench.action.navigateToLastEditLocation",
  "Open New Window": "workbench.action.newWindow",
  "Go To Next Editor": "workbench.action.nextEditor",
  "Go To Next Editor In Group": "workbench.action.nextEditorInGroup",
  "Open Editor At Index 1": "workbench.action.openEditorAtIndex1",
  "Open Editor At Index 2": "workbench.action.openEditorAtIndex2",
  "Open Editor At Index 3": "workbench.action.openEditorAtIndex3",
  "Open Editor At Index 4": "workbench.action.openEditorAtIndex4",
  "Open Editor At Index 5": "workbench.action.openEditorAtIndex5",
  "Open Editor At Index 6": "workbench.action.openEditorAtIndex6",
  "Open Editor At Index 7": "workbench.action.openEditorAtIndex7",
  "Open Editor At Index 8": "workbench.action.openEditorAtIndex8",
  "Open Editor At Index 9": "workbench.action.openEditorAtIndex9",
  "Open Global Keybindings": "workbench.action.openGlobalKeybindings",
  "Open Recent": "workbench.action.openRecent",
  "Open Settings": "workbench.action.openSettings",
  "Toggle Output": "workbench.action.output.toggleOutput",
  "Pin Editor": "workbench.action.pinEditor",
  "Go To Previous Editor": "workbench.action.previousEditor",
  "Switch To Previous Editor In Group": "workbench.action.previousEditorInGroup",
  "Quick Open File": "workbench.action.quickOpen",
  "Open Least Recently Used Editor In Group": "workbench.action.quickOpenLeastRecentlyUsedEditorInGroup",
  "Open Previous Recently Used Editor In Group": "workbench.action.quickOpenPreviousRecentlyUsedEditorInGroup",
  "Quick Open View": "workbench.action.quickOpenView",
  "Toggle Quick Chat": "workbench.action.quickchat.toggle",
  "Quit Vs Code": "workbench.action.quit",
  "Show Remote Menu": "workbench.action.remote.showMenu",
  "Reopen Closed Editor": "workbench.action.reopenClosedEditor",
  "Replace In Files": "workbench.action.replaceInFiles",
  "Toggle Search Query Details": "workbench.action.search.toggleQueryDetails",
  "Select Theme": "workbench.action.selectTheme",
  "Show All Editors": "workbench.action.showAllEditors",
  "Show All Symbols": "workbench.action.showAllSymbols",
  "Show Commands": "workbench.action.showCommands",
  "Split Editor": "workbench.action.splitEditor",
  "Split Editor Down": "workbench.action.splitEditorDown",
  "Split Editor In Group": "workbench.action.splitEditorInGroup",
  "Split Editor Left": "workbench.action.splitEditorLeft",
  "Split Editor Orthogonal": "workbench.action.splitEditorOrthogonal",
  "Split Editor Right": "workbench.action.splitEditorRight",
  "Split Editor Up": "workbench.action.splitEditorUp",
  "Switch Window": "workbench.action.switchWindow",
  "Build Tasks": "workbench.action.tasks.build",
  "Close Terminal Chat": "workbench.action.terminal.chat.close",
  "Focus Terminal Chat Input": "workbench.action.terminal.chat.focusInput",
  "Focus Terminal Chat Response": "workbench.action.terminal.chat.focusResponse",
  "Insert Command In Terminal Chat": "workbench.action.terminal.chat.insertCommand",
  "Insert First Command In Terminal Chat": "workbench.action.terminal.chat.insertFirstCommand",
  "Make Request In Terminal Chat": "workbench.action.terminal.chat.makeRequest",
  "Next From History In Terminal Chat": "workbench.action.terminal.chat.nextFromHistory",
  "Previous From History In Terminal Chat": "workbench.action.terminal.chat.previousFromHistory",
  "Run Command In Terminal Chat": "workbench.action.terminal.chat.runCommand",
  "Run First Command In Terminal Chat": "workbench.action.terminal.chat.runFirstCommand",
  "Clear Terminal Selection": "workbench.action.terminal.clearSelection",
  "Copy Terminal Selection": "workbench.action.terminal.copySelection",
  "Find Next In Terminal": "workbench.action.terminal.findNext",
  "Find Previous In Terminal": "workbench.action.terminal.findPrevious",
  "Focus Terminal": "workbench.action.terminal.focus",
  "Focus Accessible Buffer In Terminal": "workbench.action.terminal.focusAccessibleBuffer",
  "Focus Find In Terminal": "workbench.action.terminal.focusFind",
  "Focus Hover In Terminal": "workbench.action.terminal.focusHover",
  "Focus Next In Terminal": "workbench.action.terminal.focusNext",
  "Focus Next Pane In Terminal": "workbench.action.terminal.focusNextPane",
  "Focus Previous In Terminal": "workbench.action.terminal.focusPrevious",
  "Focus Previous Pane In Terminal": "workbench.action.terminal.focusPreviousPane",
  "Focus Tabs In Terminal": "workbench.action.terminal.focusTabs",
  "Go To Recent Directory In Terminal": "workbench.action.terminal.goToRecentDirectory",
  "Hide Find In Terminal": "workbench.action.terminal.hideFind",
  "Kill Active Tab In Terminal": "workbench.action.terminal.killActiveTab",
  "Kill Editor In Terminal": "workbench.action.terminal.killEditor",
  "New Terminal": "workbench.action.terminal.new",
  "Open Native Console In Terminal": "workbench.action.terminal.openNativeConsole",
  "Paste In Terminal": "workbench.action.terminal.paste",
  "Rename Active Tab In Terminal": "workbench.action.terminal.renameActiveTab",
  "Resize Pane Down In Terminal": "workbench.action.terminal.resizePaneDown",
  "Resize Pane Left In Terminal": "workbench.action.terminal.resizePaneLeft",
  "Resize Pane Right In Terminal": "workbench.action.terminal.resizePaneRight",
  "Resize Pane Up In Terminal": "workbench.action.terminal.resizePaneUp",
  "Run Recent Command In Terminal": "workbench.action.terminal.runRecentCommand",
  "Scroll Down In Terminal": "workbench.action.terminal.scrollDown",
  "Scroll Down Page In Terminal": "workbench.action.terminal.scrollDownPage",
  "Scroll To Bottom In Terminal": "workbench.action.terminal.scrollToBottom",
  "Scroll To Bottom Accessible View In Terminal": "workbench.action.terminal.scrollToBottomAccessibleView",
  "Scroll To Next Command In Terminal": "workbench.action.terminal.scrollToNextCommand",
  "Scroll To Previous Command In Terminal": "workbench.action.terminal.scrollToPreviousCommand",
  "Scroll To Top In Terminal": "workbench.action.terminal.scrollToTop",
  "Scroll To Top Accessible View In Terminal": "workbench.action.terminal.scrollToTopAccessibleView",
  "Scroll Up In Terminal": "workbench.action.terminal.scrollUp",
  "Scroll Up Page In Terminal": "workbench.action.terminal.scrollUpPage",
  "Select All In Terminal": "workbench.action.terminal.selectAll",
  "Select To Next Command In Terminal": "workbench.action.terminal.selectToNextCommand",
  "Select To Previous Command In Terminal": "workbench.action.terminal.selectToPreviousCommand",
  "Send Sequence In Terminal": "workbench.action.terminal.sendSequence",
  "Show Quick Fixes In Terminal": "workbench.action.terminal.showQuickFixes",
  "Size To Content Width In Terminal": "workbench.action.terminal.sizeToContentWidth",
  "Split Terminal": "workbench.action.terminal.split",
  "Split Active Tab In Terminal": "workbench.action.terminal.splitActiveTab",
  "Toggle Find Case Sensitive In Terminal": "workbench.action.terminal.toggleFindCaseSensitive",
  "Toggle Find Regex In Terminal": "workbench.action.terminal.toggleFindRegex",
  "Toggle Find Whole Word In Terminal": "workbench.action.terminal.toggleFindWholeWord",
  "Toggle Terminal": "workbench.action.terminal.toggleTerminal",
  "Toggle Auxiliary Bar": "workbench.action.toggleAuxiliaryBar",
  "Toggle Editor Group Layout": "workbench.action.toggleEditorGroupLayout",
  "Toggle Full Screen": "workbench.action.toggleFullScreen",
  "Toggle Maximize Editor Group": "workbench.action.toggleMaximizeEditorGroup",
  "Toggle Panel": "workbench.action.togglePanel",
  "Toggle Sidebar Visibility": "workbench.action.toggleSidebarVisibility",
  "Toggle Zen Mode": "workbench.action.toggleZenMode",
  "Unpin Editor": "workbench.action.unpinEditor",
  "Zoom In": "workbench.action.zoomIn",
  "Zoom Out": "workbench.action.zoomOut",
  "Reset Zoom": "workbench.action.zoomReset",
  "View Problems": "workbench.actions.view.problems",
  "Focus Banner": "workbench.banner.focusBanner",
  "Focus Next Action In Banner": "workbench.banner.focusNextAction",
  "Focus Previous Action In Banner": "workbench.banner.focusPreviousAction",
  "Toggle Repl In Debug": "workbench.debug.action.toggleRepl",
  "Compare With Clipboard": "workbench.files.action.compareWithClipboard",
  "Compare With Saved": "workbench.files.action.compareWithSaved",
  "Focus Open Editors View": "workbench.files.action.focusOpenEditorsView",
  "Clear Focus In Status Bar": "workbench.statusBar.clearFocus",
  "Focus First In Status Bar": "workbench.statusBar.focusFirst",
  "Focus Last In Status Bar": "workbench.statusBar.focusLast",
  "Focus Next In Status Bar": "workbench.statusBar.focusNext",
  "Focus Previous In Status Bar": "workbench.statusBar.focusPrevious",
  "View Debug": "workbench.view.debug",
  "View Explorer": "workbench.view.explorer",
  "View Extensions": "workbench.view.extensions",
  "View Scm": "workbench.view.scm",
  "View Search": "workbench.view.search",
  "Focus Next With Picker In Breadcrumbs": "breadcrumbs.focusNextWithPicker",
  "Focus Previous With Picker In Breadcrumbs": "breadcrumbs.focusPreviousWithPicker",
  "Select Editor In Breadcrumbs": "breadcrumbs.selectEditor",
  "Find Repl Input Focus In List": "list.find.replInputFocus",
  "Null Action In Notebook Cell": "notebook.cell.nullAction",
  "Select All In Notebook Cell Output": "notebook.cell.output.selectAll",
  "Move View Down": "views.moveViewDown",
  "Move View Left": "views.moveViewLeft",
  "Move View Right": "views.moveViewRight",
  "Move View Up": "views.moveViewUp",
  "Next Console In Debug": "workbench.action.debug.nextConsole",
  "Previous Console In Debug": "workbench.action.debug.prevConsole",
  "Accept Selected Suggestion In Terminal": "workbench.action.terminal.acceptSelectedSuggestion",
  "Accept Selected Suggestion Enter In Terminal": "workbench.action.terminal.acceptSelectedSuggestionEnter",
  "Clear Terminal": "workbench.action.terminal.clear",
  "Hide Suggest Widget In Terminal": "workbench.action.terminal.hideSuggestWidget",
  "Open Detected Link In Terminal": "workbench.action.terminal.openDetectedLink",
  "Select Next Page Suggestion In Terminal": "workbench.action.terminal.selectNextPageSuggestion",
  "Select Next Suggestion In Terminal": "workbench.action.terminal.selectNextSuggestion",
  "Select Previous Page Suggestion In Terminal": "workbench.action.terminal.selectPrevPageSuggestion",
  "Select Previous Suggestion In Terminal": "workbench.action.terminal.selectPrevSuggestion",
  "Clear Repl Action In Debug": "workbench.debug.panel.action.clearReplAction",
  "Pause Debug": "workbench.action.debug.pause",
  "Go To Next Command In Terminal Accessible Buffer": "workbench.action.terminal.accessibleBufferGoToNextCommand",
  "Go To Previous Command In Terminal Accessible Buffer": "workbench.action.terminal.accessibleBufferGoToPreviousCommand",
  "Rename Watch Expression In Debug": "debug.renameWatchExpression",
  "Set Variable In Debug": "debug.setVariable",
  "Toggle Breakpoint In Debug": "debug.toggleBreakpoint",
  "Paste In Files Explorer": "filesExplorer.paste",
  "Delete File": "deleteFile",
  "Go To Symbol In Editor": "editor.action.accessibleViewGoToSymbol",
  "Toggle Screen Reader Accessibility Mode In Editor": "editor.action.toggleScreenReaderAccessibilityMode",
  "Close Call Hierarchy In Editor": "editor.closeCallHierarchy",
  "Close Type Hierarchy In Editor": "editor.closeTypeHierarchy",
  "Open And Pass Focus In Explorer": "explorer.openAndPassFocus",
  "Cancel Cut In Files Explorer": "filesExplorer.cancelCut",
  "Copy In Files Explorer": "filesExplorer.copy",
  "Cut In Files Explorer": "filesExplorer.cut",
  "Open File In Explorer Without Losing Focus": "filesExplorer.openFilePreserveFocus",
  "Go To First Compressed Folder": "firstCompressedFolder",
  "Accept Changes In Inline Chat": "inlineChat.acceptChanges",
  "Go To Last Compressed Folder": "lastCompressedFolder",
  "Move File To Trash": "moveFileToTrash",
  "Go To Next Compressed Folder": "nextCompressedFolder",
  "Go To Previous Compressed Folder": "previousCompressedFolder",
  "Close Inline Remote Tunnel": "remote.tunnel.closeInline",
  "Copy Inline Remote Tunnel Address": "remote.tunnel.copyAddressInline",
  "Label Remote Tunnel": "remote.tunnel.label",
  "Rename File": "renameFile",
  "Continue Debugging": "workbench.action.debug.continue",
  "Step Into Debugging": "workbench.action.debug.stepInto",
  "Collapse Sticky Scroll List": "list.stickyScroll.collapse",
  "Select In Sticky Scroll List": "list.stickyScrollselect",
  "Toggle Expand In Sticky Scroll List": "list.stickyScrolltoggleExpand",
  "Hide Notifications List": "notifications.hideList",
  "Accept Quick Input In Background": "quickInput.acceptInBackground",
  "Go Back In Quick Input": "workbench.action.quickInputBack",
  "Navigate To Next In Editor Picker": "workbench.action.quickOpenNavigateNextInEditorPicker",
  "Navigate To Next In File Picker": "workbench.action.quickOpenNavigateNextInFilePicker",
  "Navigate To Next In Recent Files Picker": "workbench.action.quickOpenNavigateNextInRecentFilesPicker",
  "Navigate To Next In View Picker": "workbench.action.quickOpenNavigateNextInViewPicker",
  "Navigate To Previous In Editor Picker": "workbench.action.quickOpenNavigatePreviousInEditorPicker",
  "Navigate To Previous In File Picker": "workbench.action.quickOpenNavigatePreviousInFilePicker",
  "Navigate To Previous In Recent Files Picker": "workbench.action.quickOpenNavigatePreviousInRecentFilesPicker",
  "Navigate To Previous In View Picker": "workbench.action.quickOpenNavigatePreviousInViewPicker",
  "Select Next In Quick Open": "workbench.action.quickOpenSelectNext",
  "Select Previous In Quick Open": "workbench.action.quickOpenSelectPrevious",
  "Reload Window": "workbench.action.reloadWindow",
  "Search Workspace In Terminal": "workbench.action.terminal.searchWorkspace",
  "Toggle Developer Tools": "workbench.action.toggleDevTools",
  "Stop Listening To Chat": "workbench.action.chat.stopListening",
  "Stop Reading Chat Item Aloud": "workbench.action.chat.stopReadChatItemAloud",
  "Stop Dictation In Editor": "workbench.action.editorDictation.stop",
  "Stop Reading Aloud": "workbench.action.speech.stopReadAloud",
  "Start Debugging With Stop On Entry": "extension.node-debug.startWithStopOnEntry",
  "Stage Selected Ranges In Git": "git.stageSelectedRanges",
  "Show Markdown Preview": "markdown.showPreview",
  "Find References": "references-view.findReferences",
  "Unstage Selected Ranges In Git": "git.unstageSelectedRanges",
  "Show Markdown Preview To Side": "markdown.showPreviewToSide",
  "Revert Selected Ranges In Git": "git.revertSelectedRanges",
  "Show Call Hierarchy": "references-view.showCallHierarchy",
  "Generate With Github Copilot": "github.copilot.generate",
  "Apply Chat In Editor": "workbench.action.chat.applyInEditor",
  "Insert Code Block In Chat": "workbench.action.chat.insertCodeBlock",
  "Start Terminal Chat": "workbench.action.terminal.chat.start",
  "Accept Github Copilot Cursor Panel Solution": "github.copilot.acceptCursorPanelSolution",
  "Go To Previous Github Copilot Panel Solution": "github.copilot.previousPanelSolution",
  "Go To Next Github Copilot Panel Solution": "github.copilot.nextPanelSolution",
  "Trigger Inline Suggestion": "editor.action.inlineSuggest.trigger",
  "Accept Selected Code Action": "acceptSelectedCodeAction",
  "Hide Code Action Widget": "hideCodeActionWidget",
  "Preview Selected Code Action": "previewSelectedCodeAction",
  "Select Next Code Action": "selectNextCodeAction",
  "Select Previous Code Action": "selectPrevCodeAction",
  "Exit Compare Move In Diff Editor": "diffEditor.exitCompareMove",
  "Accept Inline Edits": "editor.action.inlineEdits.accept",
  "Toggle Minimap": "editor.action.toggleMinimap",
  "Toggle Line Numbers": "editor.action.toggleLineNumbers",
  "Toggle Indent Guides": "editor.action.toggleIndentGuides",
  "Toggle Render Whitespace": "editor.action.toggleRenderWhitespace",
  "Toggle Activity Bar Visibility": "workbench.action.toggleActivityBarVisibility",
  "Toggle Status Bar Visibility": "workbench.action.toggleStatusbarVisibility",
  "Toggle Tabs Visibility": "workbench.action.toggleTabsVisibility",
  "Toggle Centered Layout": "workbench.action.toggleCenteredLayout",
  "Toggle Breadcrumbs": "breadcrumbs.toggle",
  "Increase Font Size": "editor.action.fontZoomIn",
  "Decrease Font Size": "editor.action.fontZoomOut",
  "Reset Font Size": "editor.action.fontZoomReset",
  "Reveal In Explorer": "revealInExplorer",
  "Add Cursor To Line Ends": "editor.action.addCursorsToBottom",
  "Close Saved Editors": "workbench.action.closeSavedEditors",
  "Close Editors To The Left": "workbench.action.closeEditorsToTheLeft",
  "Close Editors To The Right": "workbench.action.closeEditorsToTheRight",
  "Add Selection To Previous Find Match": "editor.action.addSelectionToPreviousFindMatch",
  "Run Task": "workbench.action.tasks.runTask",
  "Configure Task": "workbench.action.tasks.configureTaskRunner"
} as const;

/**
 * Custom commands that are not part of the built-in commands.
 * Usually involves multiple steps or custom logic and entity extraction.
 */
export const CustomCommands = {
  "get screenshot": "screenshot",
  "type [text]": "type",
  "type [text] and enter": "typeAndEnter",
  "keytap enter": "enter",
  "keytap tab": "tab",
  "keytap escape": "escape",
  "keytap backspace": "backspace",
  "keytap delete": "delete",
  "keytap space": "space",
  "keytap up": "up",
  "keytap down": "down",
  "keytap left": "left",
  "keytap right": "right",
  "go to line [number]": "goToLine",
  "open file [filename]": "openFile",
  "search [text]": "search",
  "replace [text] with [text]": "replace",
} as const;

export const Commands = {
  ...BuiltInCommands,
  ...CustomCommands,
} as const;
