const { test } = require('node:test');
const assert = require('node:assert/strict');
const { once } = require('node:events');
const Module = require('node:module');
const { WebSocket } = require('ws');
let captures = 0, uploads = 0, taps = [], typed = [], modifiers = [], pointers = [], buttons = [], scrolls = [];
const connectionEvents = [];
const native = { getScreenSize: () => ({ width: 1440, height: 900 }), keyTap: (key, held = []) => { taps.push(key); modifiers = held; }, keyToggle: key => { modifiers = modifiers.filter(m => m !== key); }, moveMouse(x, y) { pointers.push([x, y]); }, mouseToggle(state, button) { buttons.push([state, button]); }, scrollMouse(x, y) { scrolls.push([x, y]); }, typeString(text) { if (!modifiers.length) typed.push(text); } };
const originalLoad = Module._load;
Module._load = function(name, ...args) {
  if (name === 'vscode') return { workspace: { isTrusted: true }, window: { showInformationMessage() {}, createOutputChannel() { return { appendLine: line => connectionEvents.push(line), dispose() {} }; } } };
  if (name === './commanding/robotjs-handlers') return { typedRobot: native };
  if (name === './native-capture') return { capturePrimaryScreen: async () => { captures++; return Buffer.alloc(4096); }, nativeResizeJpeg: async () => null };
  if (name === './jimp') return { createImage: async () => ({ width: 1440, height: 900, getBuffer: async () => Buffer.from('frame') }) };
  if (name === './commanding/command-handler') return { handleCommand() {} };
  if (name === './files/utils') return { handleFileUpload() { uploads++; } };
  return originalLoad.call(this, name, ...args);
};
const { startServer, stopServer } = require('../src/server.ts');
const { store } = require('../src/state/store.ts');
require('../src/connection-log.ts').initializeConnectionLog({ subscriptions: [] });
Module._load = originalLoad;
const token = 'c'.repeat(64);
const message = socket => once(socket, 'message').then(([data]) => JSON.parse(data.toString()));
test('extension requires pairing, streams only on demand, rejects malformed text and releases listener', async () => {
  store.setState({ server: { port: 0, isRunning: false, address: null } });
  await assert.rejects(startServer('0.0.0.0', token));
  const occupied = require('net').createServer(); occupied.listen(0, '127.0.0.1'); await once(occupied, 'listening');
  store.setState({ server: { port: occupied.address().port, isRunning: false, address: null } });
  await assert.rejects(startServer('127.0.0.1', token), /EADDRINUSE/);
  await new Promise(resolve => occupied.close(resolve));
  store.setState({ server: { port: 0, isRunning: false, address: null } });
  await startServer('127.0.0.1', token);
  const wss = store.getState().websocket.wss;
  const port = wss.address().port;
  let client;
  try {
    const bad = new WebSocket(`ws://127.0.0.1:${port}`);
    await new Promise(resolve => bad.on('error', resolve));
    const wrong = new WebSocket(`ws://127.0.0.1:${port}`, { headers: { Authorization: 'Bearer sensitive-invalid-key' } });
    await new Promise(resolve => wrong.on('error', resolve));
    const tls = require('net').connect(port, '127.0.0.1');
    await once(tls, 'connect');
    tls.write(Buffer.from([0x16, 0x03, 0x01, 0, 0]));
    await once(tls, 'close');
    assert.ok(connectionEvents.some(line => line.includes('missing pairing key')));
    assert.ok(connectionEvents.some(line => line.includes('incorrect pairing key')));
    assert.ok(connectionEvents.some(line => line.includes('TLS requested on plain WebSocket port')));
    assert.ok(connectionEvents.every(line => !line.includes(token) && !line.includes('sensitive-invalid-key')));
    assert.equal(captures, 0);
    client = new WebSocket(`ws://127.0.0.1:${port}`, { headers: { Authorization: 'Bearer ' + token } });
    const hello = message(client);
    await once(client, 'open');
    const capabilities = await hello;
    assert.equal(capabilities.type, 'server_capabilities');
    assert.equal(capabilities.features.vncSharedPort, true);
    assert.equal(capabilities.features.pty, false);
    assert.deepEqual(capabilities.features.agents, []);
    assert.equal(captures, 0);
    assert.equal(capabilities.features.heartbeat, true);
    assert.equal(capabilities.features.vncScroll, true);
    assert.equal(capabilities.features.vncRightClick, true);
    const pong = message(client); client.send(JSON.stringify({type: 'ping'}));
    assert.equal((await pong).type, 'pong');
    const rejected = message(client); client.send('{broken');
    assert.equal((await rejected).type, 'error'); assert.equal(uploads, 0);
    const frame = message(client); client.send(JSON.stringify({ type: 'vnc_start' }));
    assert.equal((await frame).type, 'screen-update'); assert.ok(captures > 0);
    const serverSocket = [...wss.clients][0];
    const { ScreenCaptureManager } = require('../src/websockets.ts');
    const manager = ScreenCaptureManager.getInstance();
    let sends = 0;
    const originalSend = serverSocket.send;
    serverSocket.send = function(...args) { sends++; return originalSend.apply(this, args); };
    Object.defineProperty(serverSocket, 'bufferedAmount', { value: 1, configurable: true });
    manager.subscribers[0](Buffer.from('blocked frame'), { width: 1440, height: 900 });
    assert.equal(sends, 0, 'backed-up sockets must not enqueue another frame');
    delete serverSocket.bufferedAmount;
    const rejectedKey = message(client); client.send(JSON.stringify({ type: 'vnc_keyboard_event', key: 'constructor' }));
    assert.equal((await rejectedKey).type, 'error'); assert.deepEqual(taps, []);
    client.send(JSON.stringify({ type: 'vnc_keyboard_event', key: 'a', modifier: ['command'] }));
    client.send(JSON.stringify({ type: 'vnc_type', text: 'after shortcut' }));
    const processed = message(client); client.send('{broken'); await processed;
    assert.deepEqual(typed, ['after shortcut']);
    assert.deepEqual(modifiers, []);
    client.send(JSON.stringify({ type: 'vnc_stop' }));
    const point = { x: 720, y: 450, screenWidth: 720, screenHeight: 450 };
    client.send(JSON.stringify({ ...point, type: 'vnc_scroll', deltaX: -2, deltaY: 3 }));
    client.send(JSON.stringify({ ...point, type: 'vnc_mouse_event', eventType: 'down', button: 'right' }));
    const drained = message(client); client.send(JSON.stringify({ type: 'ping' })); await drained;
    const { nativeScrollDelta } = require('../src/vnc-input.ts');
    assert.deepEqual(scrolls, [[nativeScrollDelta(-2), nativeScrollDelta(3)]]);
    assert.deepEqual(pointers.at(-1), [1439, 899], 'edge maps inside native screen');
    assert.deepEqual(buttons.at(-1), ['down', 'right']);
    const invalidScroll = message(client);
    client.send(JSON.stringify({ ...point, type: 'vnc_scroll', deltaX: 0, deltaY: 1000000 }));
    assert.equal((await invalidScroll).type, 'error');
    assert.equal(scrolls.length, 1, 'invalid wheel events never reach native input');
  } finally {
    const closed = client ? once(client, 'close') : Promise.resolve();
    stopServer(); await closed;
  }
  assert.deepEqual(buttons.at(-1), ['up', 'right'], 'disconnect releases held right button');
  // Rebind the exact port; old implementation leaked its HTTP listener.
  store.setState({ server: { port, isRunning: false, address: null } });
  await startServer('127.0.0.1', token); stopServer();
});

test('automatic ports preserve existing listeners and pair only with the selected instance key', async () => {
  const occupied = require('net').createServer();
  occupied.listen(0, '127.0.0.1'); await once(occupied, 'listening');
  const occupiedPort = occupied.address().port;
  let client;
  try {
    store.setState({ server: { port: occupiedPort, isRunning: false, address: null } });
    await startServer('127.0.0.1', token, { port: occupiedPort, autoPort: true, pairingTokenForPort: port => require('../src/instance.ts').tokenForPort(token, port) });
    const actual = store.getState().server.port;
    assert.notEqual(actual, occupiedPort);
    assert.equal(actual, store.getState().websocket.wss.address().port);
    assert.equal(occupied.listening, true, 'starting another window does not stop the existing server');
    const { getInstance, tokenForPort } = require('../src/instance.ts');
    const wrong = new WebSocket(`ws://127.0.0.1:${actual}`, { headers: { Authorization: 'Bearer ' + token } });
    await new Promise(resolve => wrong.once('error', resolve));
    const selectedToken = tokenForPort(token, actual);
    client = new WebSocket(`ws://127.0.0.1:${actual}`, { headers: { Authorization: 'Bearer ' + selectedToken } });
    const hello = message(client);
    await once(client, 'open');
    const capabilities = await hello;
    assert.equal(capabilities.instance.id, getInstance(actual).id);
    assert.equal(capabilities.instance.sharedDesktop, true);
    const closed = once(client, 'close'); stopServer(); await closed;
    client = undefined;
    await startServer('127.0.0.1', token, { port: actual, autoPort: true, pairingTokenForPort: port => require('../src/instance.ts').tokenForPort(token, port) });
    assert.equal(store.getState().server.port, actual, 'restart retains the chosen endpoint');
    assert.equal(tokenForPort(token, actual), selectedToken, 'restart retains its pairing key');
  } finally {
    const closed = client ? once(client, 'close') : Promise.resolve();
    stopServer(); await closed;
    await new Promise(resolve => occupied.close(resolve));
  }
});

test('stopping during startup cannot leave a hidden listener behind', async () => {
  store.setState({ server: { port: 0, isRunning: false, address: null } });
  const starting = startServer('127.0.0.1', token);
  stopServer();
  const restarting = startServer('127.0.0.1', token);
  await assert.rejects(starting, /cancelled/i);
  await restarting;
  assert.equal(store.getState().server.isRunning, true, 'an immediate restart waits for cancelled startup to finish');
  assert.ok(store.getState().websocket.wss);
  stopServer();
});
